//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_riesgos_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiccionarioRiesgosEspecifico
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Causa { get; set; }
        public string Descripcion { get; set; }
        public string Categoria { get; set; }
        public string SubCategoria { get; set; }
    }
}
