//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_riesgos_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluacion_y_Analisis
    {
        public int Id { get; set; }
        public string Tipoderiesgo { get; set; }
        public string CodigoRiesgo { get; set; }
        public string Evento { get; set; }
        public Nullable<int> Probabilidad { get; set; }
        public Nullable<int> Impacto { get; set; }
        public Nullable<double> NiveldeRiesgoInherente { get; set; }
        public string Codigo_Control_Actual { get; set; }
        public string DescripcionControlActual { get; set; }
        public Nullable<int> Disminución_Probabilidad { get; set; }
        public Nullable<int> Disminución_Impacto { get; set; }
        public Nullable<int> Probabilidad_con_Control_Actual { get; set; }
        public Nullable<int> Impacto_con_Control_Actual { get; set; }
        public Nullable<double> NiveldeRiesgoResidual1 { get; set; }
        public string Código_Control_Propuesto { get; set; }
        public string Fecha_de_Aplicación { get; set; }
        public string Descripciondelcontrolpropuesto { get; set; }
        public Nullable<int> Disminución_Probabilidad1 { get; set; }
        public Nullable<int> Disminución_Impacto1 { get; set; }
        public Nullable<int> Probabilidad_con_control_Propuesto { get; set; }
        public Nullable<int> ImpactoControlPropuesto { get; set; }
        public Nullable<double> Nivelderiesgoresidual2 { get; set; }
    }
}
