//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_riesgos_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionRiesgosEntities : DbContext
    {
        public GestionRiesgosEntities()
            : base("name=GestionRiesgosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administracion1> Administracion1 { get; set; }
        public virtual DbSet<DiccionarioRiesgosEspecifico> DiccionarioRiesgosEspecificos { get; set; }
        public virtual DbSet<Evaluacion_y_Analisis> Evaluacion_y_Analisis { get; set; }
        public virtual DbSet<Ident_Riesgos_Especificos> Ident_Riesgos_Especificos { get; set; }
        public virtual DbSet<Ident_Riesgos_Generales> Ident_Riesgos_Generales { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
