//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_riesgos_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ident_Riesgos_Especificos
    {
        public long Id { get; set; }
        public string ObjetivoProceso { get; set; }
        public string CodigoRiesgo { get; set; }
        public string Causa_específica { get; set; }
        public string Area_de_riesgo_directo_o_indirecto { get; set; }
        public string Dependencia_de_riesgo__directo_o_indirecto { get; set; }
        public string DescripcióndelaCausa { get; set; }
        public string DescripcióndelosEventos { get; set; }
        public string DescripcióndelasConsecuencias { get; set; }
        public string Fecha_de_identificación_del_riesgo { get; set; }
    }
}
