//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_riesgos_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ident_Riesgos_Generales
    {
        public int Id { get; set; }
        public string CodigodeRiesgo { get; set; }
        public string ObjetivoProceso { get; set; }
        public string CodigoCausa { get; set; }
        public string CausaFactor { get; set; }
        public string Descripcion { get; set; }
        public string Fuente { get; set; }
        public string Categoría__del_Factor { get; set; }
        public string SubCategoría_del_Factor { get; set; }
        public string DescripcióndelaCausa { get; set; }
        public string DescripcióndelEvento { get; set; }
        public string DescripcióndelaConsecuencia { get; set; }
        public string Fecha_de_identificación_del_riesgo { get; set; }
    }
}
